"""Interfaces for external capabilities."""

from alignment_memory.ports.github import (
    ALLOWED_ACTOR_ASSOCIATIONS,
    ActorAssociation,
    CollectedSource,
    GitHubAdapterError,
    GitHubAuthenticationError,
    GitHubPermissionError,
    GitHubPort,
    GitHubRateLimitError,
    GitHubRepositoryRef,
    GitHubResponseError,
    GitHubSourceType,
    GitHubTimeoutError,
    SourceBatch,
)
from alignment_memory.ports.llm import (
    AnalysisDocument,
    AnalysisRequest,
    LlmAdapterError,
    LlmAnalysis,
    LlmAuthenticationError,
    LlmPort,
    LlmProviderError,
    LlmTimeoutError,
    LlmUsage,
    LlmValidationError,
    validate_analysis_result_evidence,
)
from alignment_memory.ports.repositories import (
    AnalysisRunRepository,
    CorrectionRepository,
    JobRepository,
    KnowledgeRepository,
    PersistenceRepository,
    SourceRepository,
)

__all__ = [
    "ALLOWED_ACTOR_ASSOCIATIONS",
    "ActorAssociation",
    "AnalysisDocument",
    "AnalysisRequest",
    "AnalysisRunRepository",
    "CollectedSource",
    "CorrectionRepository",
    "GitHubAdapterError",
    "GitHubAuthenticationError",
    "GitHubPermissionError",
    "GitHubPort",
    "GitHubRateLimitError",
    "GitHubRepositoryRef",
    "GitHubResponseError",
    "GitHubSourceType",
    "GitHubTimeoutError",
    "JobRepository",
    "KnowledgeRepository",
    "LlmAdapterError",
    "LlmAnalysis",
    "LlmAuthenticationError",
    "LlmPort",
    "LlmProviderError",
    "LlmTimeoutError",
    "LlmUsage",
    "LlmValidationError",
    "PersistenceRepository",
    "SourceBatch",
    "SourceRepository",
    "validate_analysis_result_evidence",
]
